import { ThemeProvider } from "@/components/providers/theme-provider";
import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} bg-background min-h-screen from-[#43434330] via-[#32323230] via-25% font-sans antialiased dark:bg-gradient-to-b`}
			>
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
					<main className="mx-auto max-w-2xl py-4 md:pt-10">{children}</main>
				</ThemeProvider>
				{process.env.NODE_ENV === "production" && <>{/* TODO: Add analytics */}</>}
			</body>
		</html>
	);
}
